use anyhow::Result;
use console::style;
use flate2::Compression;
use flate2::write::GzEncoder;
use std::fs::{self, File};
use std::io::Write;
use tar::Builder;

/// Create a single-file Self-Extracting (.sh) installer.
/// It bundles everything in the bundle_dir into a binary payload at the end of a bash script.
pub fn create_sfx(bundle_dir: &str, output_path: &str) -> Result<()> {
    println!(
        "  {} Building single-file SFX installer...",
        style("📦").cyan()
    );

    // 1. Create a tar.gz of the bundle directory in memory
    let mut tar_gz_buffer = Vec::new();
    {
        let enc = GzEncoder::new(&mut tar_gz_buffer, Compression::best());
        let mut tar = Builder::new(enc);
        tar.append_dir_all(".", bundle_dir)?;
        tar.finish()?;
    }

    // 2. Define the shell stub header
    let stub_header = r#"#!/bin/bash
# 3x-ui Offline Self-Extracting Installer
# Generated by xui-offline-builder
set -e

# Colors
C_BLU='\033[0;34m'
C_CYN='\033[0;36m'
C_GRN='\033[0;32m'
C_YLW='\033[1;33m'
C_RED='\033[0;31m'
C_RST='\033[0m'

# Configuration
TMP_BASE="/tmp"
INSTALL_DIR="$TMP_BASE/xui-installer-$$"

# Cleanup on exit
trap "rm -rf $INSTALL_DIR" EXIT

echo -e "${C_CYN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${C_RST}"
echo -e "${C_CYN}   🚀  3x-ui Offline Self-Extracting Installer${C_RST}"
echo -e "${C_CYN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${C_RST}"
echo -e ""

echo -e "${C_BLU}This package will extract and launch the 3x-ui offline installer.${C_RST}"
read -p "📦 Do you want to proceed? [y/N]: " confirm
if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
    echo -e "${C_RED}Aborted.${C_RST}"
    exit 0
fi
echo -e ""

# Find the line where binary data starts
PAYLOAD_LINE=$(awk '/^__BINARY_DATA_BELOW__/ {print NR + 1; exit 0; }' "$0")

if [ -z "$PAYLOAD_LINE" ]; then
    echo -e "${C_RED}❌ Error: Could not find payload start.${C_RST}"
    exit 1
fi

echo -e "${C_BLU}📦  Step 1/2: Extracting bundle content...${C_RST}"
mkdir -p "$INSTALL_DIR"

# Extract binary payload
if tail -n +$PAYLOAD_LINE "$0" | tar -xz -C "$INSTALL_DIR" 2>/dev/null; then
    echo -e "${C_GRN}✓  Content extracted successfully.${C_RST}"
else
    echo -e "${C_RED}❌ Error: Extraction failed.${C_RST}"
    exit 1
fi

echo -e ""
echo -e "${C_BLU}🚀  Step 2/2: Launching installation engine...${C_RST}"
cd "$INSTALL_DIR"

if [ -f "./install.sh" ]; then
    echo -e "${C_YLW}------------------------------------------------------------${C_RST}"
    bash ./install.sh
    echo -e "${C_YLW}------------------------------------------------------------${C_RST}"
else
    echo -e "${C_RED}❌ Error: Critical file 'install.sh' not found in bundle.${C_RST}"
    exit 1
fi

echo -e ""
echo -e "${C_GRN}✨  SFX process completed.${C_RST}"
echo -e "${C_CYN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${C_RST}"

exit 0
__BINARY_DATA_BELOW__
"#;

    // 3. Write stub header + binary payload to the final .sh file
    let mut f = File::create(output_path)?;
    f.write_all(stub_header.as_bytes())?;
    f.write_all(&tar_gz_buffer)?;

    // 4. Make the output file executable
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = fs::metadata(output_path)?.permissions();
        perms.set_mode(0o755);
        fs::set_permissions(output_path, perms)?;
    }

    let size_mb = tar_gz_buffer.len() as f64 / 1024.0 / 1024.0;
    println!(
        "  {} SFX file created: {} ({:.2} MB)",
        style("✓").green(),
        style(output_path).yellow().bold(),
        size_mb
    );

    Ok(())
}
